### ISSUE TITLE
[10.0] Bug 500:  current_lead_phone is inconsistent with crm.lead.phone

### ISSUE THREAD

**Issue by collex100** [OCA/connector-telephony#124]
Impacted versions:10

Steps to reproduce:

Installed modules:

asterisk_click2dial
base_phone
crm_phone
event_phone
hr_recruitment_phone
hr_phone

After a while, I got a 500 error.

Current behavior:
In the log there is this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1454, in dispatch
    odoo.registry(db).check_signaling()
  File "/usr/lib/python2.7/site-packages/odoo/__init__.py", line 55, in registry
    return modules.registry.Registry(database_name)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 55, in __new__
    return cls.new(db_name)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 339, in load_modules
    registry.setup_models(cr)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 293, in setup_models
    model._setup_fields(partial)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 2831, in _setup_fields
    field.setup_full(self)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 491, in setup_full
    self._setup_related_full(model)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 536, in _setup_related_full
    raise TypeError("Type of related field %s is inconsistent with %s" % (self, field))
TypeError: Type of related field number.not.found.current_lead_phone is inconsistent with crm.lead.phone
```

Expected behavior:
What would module operated successfully

Thanks if you can help with this problem.

**Comment by collex100** [comment]
There was some conflict with the other module.
