### ISSUE TITLE
[v12] Error with Chrome call

### ISSUE THREAD

**Issue by moblesmarti** [OCA/connector-telephony#174]
With Chrome in Odoo Community v12, when I do a call and catch the phone apear this error, that not problem for the call. On Firefox is not apear it.

Error:
Uncaught TypeError: this.do_action is not a function

http://192.168.1.51:8069/web/content/1087-b53649a/web.assets_backend.js:3311
Rastreo de error:
TypeError: this.do_action is not a function
    at Object.<anonymous> (http://192.168.1.51:8069/web/content/1087-b53649a/web.assets_backend.js:3311:1312)
    at fire (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:803:56)
    at Object.<anonymous> (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:3587:448)
    at Object.<anonymous> (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:802:681)
    at fire (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:803:56)
    at fire (http://192.168.1.51:8069/web/content/764-8c3c974/web.assets_common.js:796:299)

**Comment by pedrobaeza** [comment]
Sorry, but you should explain better the steps to reproduce the problem.

**Comment by moblesmarti** [comment]
I have the Odoo 12 version with the phone connector to an Issabel 4 server.

In the Chrome browser I make a call to a client I get the error described above, which does not affect the call.

I have tried with the Firefox browser and that error does not come out.

![error llamada](https://user-images.githubusercontent.com/12881456/49935912-a8993400-fed2-11e8-8c04-240e1ad9b5ac.png)

**Comment by MindSetLib** [comment]
I have the same issue. My SIP server is asterisk.

When I press to any number get this error

Ошибка:
Uncaught TypeError: this.do_action is not a function

http://jazzlight.tech:8069/web/content/586-0c6708f/web.assets_backend.js:3351
Отслеживающий:
TypeError: this.do_action is not a function
    at Object.<anonymous> (http://jazzlight.tech:8069/web/content/586-0c6708f/web.assets_backend.js:3351:1312)
    at fire (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:803:56)
    at Object.<anonymous> (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:3587:448)
    at Object.<anonymous> (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:802:681)
    at fire (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:803:56)
    at fire (http://jazzlight.tech:8069/web/content/585-82e0702/web.assets_common.js:796:299)

**Comment by gokhanerdogdu** [comment]
Same problem also occurs in V11 version. 

Click the number to make click2call, then open the call from the softphone and the problem occurs. The problem is occuring when the system is trying to open the Log Call window. Thus, Log Call windows can not open during the call.

![image](https://user-images.githubusercontent.com/20369981/52741932-a3965500-2fe7-11e9-9375-d0b0d9d426a8.png)
