### ISSUE TITLE
Error when i install [asterisk_click2dial] [Odoo 10]

### ISSUE THREAD

**Issue by rauldb-br** [OCA/connector-telephony#207]
Hello,

I have install [ pip install odoo10-addons-oca-connector-telephony ]

Then i download to my addons-extra [ 
wget https://github.com/OCA/connector-telephony/archive/10.0.zip
]

Then i search in Odoo [ asterisk_click2dial ], i click install and i have this ERROR : 

`Uncaught Error: QWeb2: Template 'asterisk_click2dial.OpenCaller' not found`

`http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:2908
Rastreo de error:
Error: QWeb2: Template 'asterisk_click2dial.OpenCaller' not found
    at Object.exception (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:2908:7)
    at Engine._render (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:2953:103)
    at Engine.render (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:2949:151)
    at Class.renderElement (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:3119:1073)
    at http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:3119:917
    at http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:547:681
    at fire (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:541:299)
    at Object.add [as done] (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:542:467)
    at Array.<anonymous> (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:547:649)
    at Function.each (http://185.14.58.100:8069/web/content/6631-8595e50/web.assets_common.js:370:767)`

**Comment by f1-outsourcing** [comment]
I have similar with odoo 12

Error: QWeb2: Template 'asterisk_click2dial.systray.OpenCaller' not found

**Comment by f1-outsourcing** [comment]
Currently working with suitecrm, looks more professional
