### ISSUE TITLE
Migration to v13

### ISSUE THREAD

**Issue by smnmdd** [OCA/connector-telephony#224]
Hello
I tried to install it on odoo community version 13, but it was not working, there is no installation for it in odoo.

**Comment by mohbadar** [comment]
Hi, is there any plan to migrate all the modules in this repository to odoo 13 soon?

**Comment by sergioeix** [comment]
I am testing it on 13 and it works but i have an issue with incoming call, no popup its raised and if you click on the phone icon of the status bar i am getting an error, i thing the issue is on base_phone module.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 625, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 311, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 670, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 351, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 340, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/connector-telephony/asterisk_click2dial/controller.py", line 16, in get_record_from_my_channel
    res = http.request.env['asterisk.server'].get_record_from_my_channel()
  File "/opt/odoo13/connector-telephony/asterisk_click2dial/models/asterisk_server.py", line 230, in get_record_from_my_channel
    record = self.env['phone.common'].get_record_from_phone_number(
  File "/opt/odoo13/odoo-oca/base_phone/models/phone_common.py", line 78, in get_record_from_phone_number
    self._cr.execute(sql, tuple(sql_args))
  File "/opt/odoo13/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
TypeError: argument 1 must be a string or unicode object: got tuple instead
