### ISSUE TITLE
[14] Frontend error

### ISSUE THREAD

**Issue by Gretel5X** [OCA/connector-telephony#260]
## Module
click2dial
## Describe the bug
After installation of the module and sometimes (appears random to me) when navigating Odoo, an error message appears:
```
Traceback:
Error: QWeb2: Template 'asterisk_click2dial.systray.OpenCaller' not found
    at Object.exception (http://odoo.local/web/content/941-9f0c94a/web.assets_common.js:4417:7)
    at Engine._render (http://odoo.local/web/content/941-9f0c94a/web.assets_common.js:4462:103)
    at Engine.render (http://odoo.local/web/content/941-9f0c94a/web.assets_common.js:4458:151)
    at Class.renderElement (http://odoo.local/web/content/941-9f0c94a/web.assets_common.js:4987:775)
    at http://odoo.local/web/content/941-9f0c94a/web.assets_common.js:4997:6
```
After closing the message, the front end is completely empty, just the header with the selection drop-down in the upper left corner is visible.

## To Reproduce
**Affected versions**:
Odoo Version 14 with branch 14.0 of the connector repo
1. Install the module
2. Navigate Odoo :/

**Expected behavior**
No error

**Additional context**
Running Odoo 14 on Docker

**Comment by Gretel5X** [comment]
After reinstalling the module, the error did not occur again.
