### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by SuNounix** [OCA/connector-telephony#324]
Odoo 16
Debian 12
clic2dial work like a charm

Hi,

i've following this instruction : https://akretion.com/fr/open-source-contributions/odoo-asterisk-voip-connector

i have an error when i test the script :

```
# echo \"agi_callerid:0141931242\"| set_name_incoming_timeout.sh
ARGS: ['/usr/local/bin/set_name_agi.py', '--ssl', '--server', 'MY_ODOO_SERVER', '--database', 'db_odoo', '--username', 'MY_USERNAME', '--password', 'MY_PASSWORD']
ENV LINE: "agi_callerid:0141931242"
ENV LINE: 
class AGI: self.env = {'"agi_callerid': '0141931242"'}
Traceback (most recent call last):
  File "/usr/local/bin/set_name_agi.py", line 394, in <module>
    main(args)
  File "/usr/local/binjoin/set_name_agi.py", line 212, in main
    phone_number = agi.env["agi_callerid"]
                   ~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'agi_callerid'

```
```
# pip3 list | grep -e 'Odoo' -e 'pyst'
OdooRPC            0.9.0
pyst2              0.5.1

```

I forgot something ?

Thanks for your help

**Comment by SuNounix** [comment]
hummm with this :

`# echo "agi_callerid:0141931242"| set_name_incoming_timeout.sh`

i have this result :

```
ARGS: ['/usr/local/bin/set_name_agi.py', '--ssl', '--server', 'MY_ODOO_SERVER', '--database', 'db_odoo', '--username', 'MY_USERNAME', '--password', 'MY_PASSWORD']
ENV LINE: agi_callerid:0141931242
ENV LINE: 
class AGI: self.env = {'agi_callerid': '0141931242'}
    COMMAND: VERBOSE "Phone number = 0141931242" 1
VERBOSE "Phone number = 0141931242" 1
    RESULT_LINE: 
Traceback (most recent call last):
  File "/usr/local/bin/set_name_agi.py", line 394, in <module>
    main(args)
  File "/usr/local/bin/set_name_agi.py", line 223, in main
    agi.verbose("Phone number = %s" % phone_number)
  File "/usr/local/lib/python3.11/dist-packages/asterisk/agi.py", line 628, in verbose
    self.execute('VERBOSE', self._quote(message), level)
  File "/usr/local/lib/python3.11/dist-packages/asterisk/agi.py", line 150, in execute
    return self.get_result()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/asterisk/agi.py", line 180, in get_result
    code = int(code)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```
