### ISSUE TITLE
Field `sel_groups_12` does not exist

### ISSUE THREAD

**Issue by paulmestereaga** [OCA/connector-telephony#35]
After updating base_phone addon I get an internal server error when I access Odoo 8. Here is the log:

2015-03-30 14:03:42,435 17475 INFO erp openerp.modules.loading: loading 1 modules...
2015-03-30 14:03:42,444 17475 INFO erp openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
2015-03-30 14:03:42,469 17475 INFO erp openerp.modules.loading: loading 52 modules...
2015-03-30 14:03:42,697 17475 INFO erp openerp.modules.module: module base_phone: creating or updating database tables
2015-03-30 14:03:42,772 17475 INFO erp openerp.modules.loading: loading base_phone/security/phone_security.xml
2015-03-30 14:03:42,775 17475 INFO erp openerp.modules.loading: loading base_phone/security/ir.model.access.csv
2015-03-30 14:03:42,785 17475 INFO erp openerp.modules.loading: loading base_phone/res_partner_view.xml
2015-03-30 14:03:42,860 17475 INFO erp openerp.modules.loading: loading base_phone/res_company_view.xml
2015-03-30 14:03:42,883 17475 INFO erp openerp.modules.loading: loading base_phone/res_users_view.xml
2015-03-30 14:03:42,926 17475 ERROR erp openerp.addons.base.ir.ir_ui_view: Field `sel_groups_12` does not exist

Error context:
View `base_phone.res.users.telephony_tab`
[view_id: 765, xml_id: base_phone.view_users_form, model: res.users, parent_id: 153]
2015-03-30 14:03:42,929 17475 INFO erp werkzeug: 10.0.100.82 - - [30/Mar/2015 14:03:42] "GET /web HTTP/1.1" 500 -
2015-03-30 14:03:42,943 17475 ERROR erp werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1280, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1254, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1254, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1254, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1412, in dispatch
    ir_http = request.registry['ir.http']
  File "/opt/odoo/openerp/http.py", line 339, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/opt/odoo/openerp/modules/registry.py", line 335, in get
    update_module)
  File "/opt/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1042, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 282, in write
    context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3761, in write
    self._write(old_vals)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3932, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 1280, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `sel_groups_12` does not exist

Error context:
View `base_phone.res.users.telephony_tab`
[view_id: 765, xml_id: base_phone.view_users_form, model: res.users, parent_id: 153]" while parsing /opt/odoo/.local/share/Odoo/addons/8.0/base_phone/res_users_view.xml:11, near
<record id="view_users_form" model="ir.ui.view">
    <field name="name">base_phone.res.users.telephony_tab</field>
    <field name="model">res.users</field>
    <field name="inherit_id" ref="base.view_users_form"/>
    <field name="arch" type="xml">
        <notebook>
            <page string="Telephony" name="phone" invisible="1" position="inside">
            
                <group name="phone-preferences" string="Telephony Preferences">
                </group>
            </page>
        </notebook>
    </field>
</record>

**Comment by alexis-via** [comment]
Restart odoo with "-u all" and it will solve the issue.

It's a pb I already faced and it's quite strange.

**Comment by alexis-via** [comment]
As explained on the bug report I just made on odoo, a workaround is to edit `base_phone/__openerp__.py` and add a dependency on the 'share' module. Very strange !!!

**Comment by paulmestereaga** [comment]
Thanks for the update!

**Comment by alexis-via** [comment]
I prefer to keep this bug report open until we find a proper solution for the user, either in our code or in the official addons.

**Comment by Abdullah1353** [comment]
i am having this same issue but i am using windows can u tell me how to solve this on that?
