### ISSUE TITLE
Inbound number that does not match a partner results in error.

### ISSUE THREAD

**Issue by jaredkipe** [OCA/connector-telephony#40]
This may be a configuration issue, but I haven't been able to find a place that would help.

```
Traceback (most recent call last):
  File "/share/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/share/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/share/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/share/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/share/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/share/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/share/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/share/odoo/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/share/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/share/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/share/scg-odoo-community/connector-telephony/base_phone/wizard/number_not_found.py", line 64, in default_get
    cr, uid, None, {'phone': res.get('calling_number')}, context=context)
  File "/share/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/share/scg-odoo-community/connector-telephony/base_phone/base_phone.py", line 38, in _generic_reformat_phonenumbers
    assert isinstance(self._country_field, (str, unicode, type(None))),\
AttributeError: 'phone.common' object has no attribute '_country_field'
```

**Comment by jaredkipe** [comment]
I added another assert above the one that was failing like:

``` python
assert hasattr(self, '_country_field'), 'Object missing _country_field for object "' + str(self) + '"'
```

which gives a similar stacktrace but with the following

```
AssertionError: Object missing _country_field for object "phone.common"
```

Later down this file, there is an extension to 'res.partner' that mentions phone.common...

**Comment by jaredkipe** [comment]
I missed that the _name field of PhoneCommon was 'phone.common' and it looks like this file attempts to extend 'res.partner' and 'phone.common' with the new fields like '_country_field' in the class ResPartner (in the same file)

**Comment by jaredkipe** [comment]
The above is now evident to me upon reading the original stack trace again.

**Comment by jaredkipe** [comment]
Trying to 'hack' around it and just let the form display by appending to PhoneCommon._generic_reformat_phonenumbers

``` python
        if not hasattr(self, '_country_field'):
            return vals
```

yields this stack trace  (aka doesn't work)

```
Traceback (most recent call last):
  File "/share/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/share/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/share/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/share/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/share/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/share/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/share/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/share/odoo/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/share/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/share/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/share/scg-odoo-community/connector-telephony/base_phone/wizard/number_not_found.py", line 65, in default_get
    parsed_num = phonenumbers.parse(convert.get('phone'))
  File "/usr/local/lib/python2.7/dist-packages/phonenumbers/phonenumberutil.py", line 2450, in parse
    "Missing or invalid default region.")
NumberParseException: (0) Missing or invalid default region.
```

It appears that the _inherits in this module's ResPartner class is not applying to this module's PhoneCommon class.

**Comment by alexis-via** [comment]
@jaredkipe 
Could you try with the (untested) patch in the PR #41 ?

**Comment by jaredkipe** [comment]
Confirmed working, thank you!

That makes a lot of sense now and I actually found that and thought about changing it, but without a reason I didn't do it.
Obviously the reason is that you don't 'really' want to ever instantiate the abstract class.

Thanks again!

**Comment by alexis-via** [comment]
@jaredkipe To help on the merge of the PR #41, could you do a :+1: in the comments of the PR ?
