### ISSUE TITLE
Banner Mismatch

### ISSUE THREAD

**Issue by AidenAndrews** [OCA/connector-telephony#48]
Got past issue with python libraries attempted connection to asterisk manager interface and odoo throws this error in the logs.

2015-05-25 19:20:48,548 899 ERROR live openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 802, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 402, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/asterisk_click2dial/asterisk_click2dial.py", line 228, in test_ami_connection
    _("Here is the error message: %s" % e))
except_orm: (u'Connection Test Failed!', u"Here is the error message: banner incorrect; got 'Asterisk Call Manager/2.5.0\r\n', expected one of ['As$

And this error using the gui Here is the error message: banner incorrect; got 'Asterisk Call Manager/2.5.0\r\n', expected one of ['Asterisk Call Manager/1.0\r\n', 'Asterisk Call Manager/1.1\r\n', 'Asterisk Call Manager/1.2\r\n', 'Asterisk Call Manager/1.3\r\n']

Asterisk version 12.8.2, freepbx version 12.0.65, AMI Version 2.5.0 ubuntu server 14.04

**Comment by alexis-via** [comment]
It means that the py-Asterisk lib needs to be updated. 

If you take the latest version of the py-Asterisk lib from github https://github.com/jeansch/py-asterisk it should work, according to my rapid look at the source code.
