### ISSUE TITLE
Testing AMI Connection Issue

### ISSUE THREAD

**Issue by AidenAndrews** [OCA/connector-telephony#50]
Fresh install from git repo's including git repos of dependancies.

2015-06-18 11:36:23,467 28946 INFO live werkzeug: 10.0.0.5 - - [18/Jun/2015 11:36:23] "POST /web/menu/load_needaction HTTP/1.1" 200 -
2015-06-18 11:36:25,118 28946 ERROR live openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/asterisk_click2dial/asterisk_click2dial.py", line 228, in test_ami_connection
    _("Here is the error message: %s" % e))
except_orm: (u'Connection Test Failed!', u"Here is the error message: 'NoneType' object has no attribute 'Manager'")
2015-06-18 11:36:25,120 28946 INFO live werkzeug: 10.0.0.5 - - [18/Jun/2015 11:36:25] "POST /web/dataset/call_button HTTP/1.1" 200 -

**Comment by alexis-via** [comment]
Did you install the "py-Asterisk" python lib ?

**Comment by AidenAndrews** [comment]
Yes straight from github. It wouldn't let me install it without it
pip freeze show's py-Asterisk==0.5.3

**Comment by alexis-via** [comment]
I made a test with some up-to-date code, and it works well ; I don't have the cash when I test the AMI connexion.

Open a python console and do:
from Asterisk import Manager

and tell me if it works

**Comment by AidenAndrews** [comment]
Here is a copy and paste from ssh.
root@loc1:~# python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from Asterisk import Manager
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/Asterisk/Manager.py", line 8
> > >     from **future** import absolute_import
> > > SyntaxError: from **future** imports must occur at the beginning of the file

**Comment by AidenAndrews** [comment]
Turn's out the author had his information at the beginning of several of the python modules files. This caused a syntax error. I deleted the authors signature on the top of the files on my staging server ran an update on odoo and AMI is connecting now. Will be pushing a merge with the information on python module dev's github. Marking as closed.
