### ISSUE TITLE
Is it possible to install this on Odoo 8

### ISSUE THREAD

**Issue by jl2035** [OCA/connector-telephony#71]
I'm getting some python error when installing asterisk_click2dial module.

I copy asterisk_click2dial and base_phone to /opt/odoo/odoo/addons, than in admin dashboard I can see "Asterisk Click2dial" module and I can click on the Install button, but I get this popup:

```
OpenERP Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 1047, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3972, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4153, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1294, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `state` does not exist

Error context:
View `reformat_all_phonenumbers.form`
[view_id: 419, xml_id: n/a, model: reformat.all.phonenumbers, parent_id: n/a]" while parsing /opt/odoo/odoo/addons/base_phone/wizard/reformat_all_phonenumbers_view.xml:11, near
<record id="reformat_all_phonenumbers_form" model="ir.ui.view">
    <field name="name">reformat_all_phonenumbers.form</field>
    <field name="model">reformat.all.phonenumbers</field>
    <field name="arch" type="xml">
        <form string="Reformat all phone numbers">
            <group name="main">
                <label string="This wizard reformats the phone, mobile and fax numbers of all partners in standard international format e.g. +33141981242" colspan="2" states="draft"/>
                <label colspan="2" string="Phone numbers that couldn't be reformatted:" states="done"/>
                <field name="phonenumbers_not_reformatted" colspan="2" nolabel="1" states="done"/>
                <field name="state" invisible="1"/>
            </group>
            <footer>
                <button name="run_reformat_all_phonenumbers" string="Reformat all phone numbers" type="object" class="oe_highlight" states="draft"/>
                <button name="action_next" type="object" string="Close" class="oe_highlight" states="done"/>
                <button special="cancel" string="Cancel" class="oe_link" states="draft"/>
            </footer>
        </form>
    </field>
</record>
```

**Comment by alexis-via** [comment]
Where did you get the code ?
Please get the good code from github.. and it will work well on Odoo 8.

**Comment by jl2035** [comment]
The code was from the website.

Now I've tried cloning this repo.

Now there's no error/popup after i click Install button, but nothing happens. Module does not get installed. It appears under "Apply Schedule Upgrade", but even after clicking Confirm also nothing.

**Comment by jl2035** [comment]
I have tried a few things with no success.
1. I tried to install from the "8.0" branch of this repo, but I still get that stupid popup with python traceback.
2. I also have Odoo 9 installed on other machine, so decided to try that. I used the "9.0" branch and downloaded the module. Then copied asterisk_click2dial and base_phone to /opt/odoo/odoo-server/addons, but Odoo doesn't see those two under the modules list. So I'm also stuck here.

Pure pain, I really want to see this module in action.. :(

**Comment by jl2035** [comment]
Giving up.. :(

**Comment by alexis-via** [comment]
The module hasn't been ported to v9 yet, that's why there is a key "'installable': False in **openerp**.py.

I think you should learn more about the technical aspects of Odoo and maybe get some training or find a mentor to help you starting. But asterisk_click2dial works well on Odoo v8, I can confirm you that.

**Comment by jl2035** [comment]
Well I had a fresh installation of v8 and tried to install asterisk_click2dial package from the website and from the repo.

Can you at least tell anything from the stacktrace I provided? What could be the reason I'm getting that?

**Comment by alexis-via** [comment]
Could you send all the logs from the start of the Odoo server until the backtrace ? My guess is that this error is NOT the first error, and the first error is always the real cause of the problem. I just tried again with an up-to-date odoo8 and I can install the asterisk_click2dial module without problems:

```
2015-11-26 14:34:12,945 9047 INFO o8_test2 openerp.modules.loading: loading 79 modules...
2015-11-26 14:34:13,275 9047 INFO o8_test2 openerp.modules.loading: 79 modules loaded in 0.33s, 0 queries
2015-11-26 14:34:13,281 9047 INFO o8_test2 openerp.modules.loading: loading 81 modules...
2015-11-26 14:34:14,177 9047 INFO o8_test2 openerp.modules.module: module base_phone: creating or updating database tables
2015-11-26 14:34:14,402 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/security/phone_security.xml
2015-11-26 14:34:14,525 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/security/ir.model.access.csv
2015-11-26 14:34:14,551 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/res_partner_view.xml
2015-11-26 14:34:14,734 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/res_company_view.xml
2015-11-26 14:34:14,800 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/res_users_view.xml
2015-11-26 14:34:14,959 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/wizard/reformat_all_phonenumbers_view.xml
2015-11-26 14:34:15,037 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/wizard/number_not_found_view.xml
2015-11-26 14:34:15,056 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/web_phone.xml
2015-11-26 14:34:15,181 9047 INFO o8_test2 openerp.modules.loading: loading base_phone/base_phone_demo.xml
2015-11-26 14:34:15,688 9047 INFO o8_test2 openerp.addons.base.ir.ir_translation: module base_phone: loading translation file (fr) for language fr_FR
2015-11-26 14:34:15,688 9047 INFO o8_test2 openerp.tools.translate: loading /home/alexis/new_boite/dev/telephony8/base_phone/i18n/fr.po
2015-11-26 14:34:16,728 9047 INFO o8_test2 openerp.modules.module: module asterisk_click2dial: creating or updating database tables
2015-11-26 14:34:16,901 9047 INFO o8_test2 openerp.addons.auth_crypt.auth_crypt: Hashing passwords, may be slow for databases with many users...
2015-11-26 14:34:16,928 9047 INFO o8_test2 openerp.modules.loading: loading asterisk_click2dial/asterisk_server_view.xml
2015-11-26 14:34:17,015 9047 INFO o8_test2 openerp.modules.loading: loading asterisk_click2dial/res_users_view.xml
2015-11-26 14:34:17,109 9047 INFO o8_test2 openerp.modules.loading: loading asterisk_click2dial/security/ir.model.access.csv
2015-11-26 14:34:17,142 9047 INFO o8_test2 openerp.modules.loading: loading asterisk_click2dial/web_asterisk_click2dial.xml
2015-11-26 14:34:17,263 9047 INFO o8_test2 openerp.modules.loading: loading asterisk_click2dial/asterisk_click2dial_demo.xml
2015-11-26 14:34:17,536 9047 INFO o8_test2 openerp.addons.base.ir.ir_translation: module asterisk_click2dial: loading base translation file en for language en_US
2015-11-26 14:34:17,536 9047 INFO o8_test2 openerp.tools.translate: loading /home/alexis/new_boite/dev/telephony8/asterisk_click2dial/i18n/en.po
2015-11-26 14:34:17,580 9047 INFO o8_test2 openerp.addons.base.ir.ir_translation: module asterisk_click2dial: loading translation file (fr) for language fr_FR
2015-11-26 14:34:17,581 9047 INFO o8_test2 openerp.tools.translate: loading /home/alexis/new_boite/dev/telephony8/asterisk_click2dial/i18n/fr.po
2015-11-26 14:34:17,640 9047 INFO o8_test2 openerp.modules.loading: 81 modules loaded in 4.36s, 0 queries
2015-11-26 14:34:18,985 9047 INFO o8_test2 openerp.modules.loading: Modules loaded.
```

**Comment by jl2035** [comment]
This was moths ago, so I'll just close the issue.
