### ISSUE TITLE
__init__() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by ghost** [OCA/connector-telephony#81]
When I click on Dial I get this error:
Click to dial with Asterisk failed.
Here is the error: '**init**() takes exactly 2 arguments (1 given)'

Here is what the logs say:
2016-02-18 22:29:25,546 8879 ERROR teamlocal openerp.addons.asterisk_click2dial.asterisk_click2dial: Error in the Originate request to Asterisk server 104.130.1.227
2016-02-18 22:29:25,547 8879 ERROR teamlocal openerp.addons.asterisk_click2dial.asterisk_click2dial: Here are the details of the error: '**init**() takes exactly 2 arguments (1 given)'
2016-02-18 22:29:25,654 8879 ERROR teamlocal openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/custom/addons/base_phone/controller.py", line 33, in click2dial
    'click2dial_id': click2dial_id,
  File "/opt/odoo/odoo-server/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/custom/addons/crm_phone/crm_phone.py", line 105, in click2dial
    res = super(PhoneCommon, self).click2dial(erp_number)
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/custom/addons/asterisk_click2dial/asterisk_click2dial.py", line 459, in click2dial
    % unicode(e))

Which points at this line:
ast_manager.Originate(
                channel,
                context=ast_server.context,
                extension=ast_number,
                priority=str(ast_server.extension_priority),
                timeout=str(ast_server.wait_time \* 1000),
                caller_id=user.callerid,
                account=user.cdraccount,
                variable=variable)

I have tried altering this call in many ways to no avail.

**Comment by sysnoo** [comment]
Hi There,
I am having similar issue.
Any solution?

**Comment by ghost** [comment]
This error is actually from the py-asterisk module when the AMI receives a permission denied error. Line 407 /usr/local/lib/python2.7/dist-packages/Asterisk/Manager.py on this file tries to raise an error for permission denied incorrectly.

**Comment by sysnoo** [comment]
Humm, and how about this log?

Click to dial with Asterisk failed.
Here is the error: '**init**() takes exactly 2 arguments (1 given)'
Traceback (most recent call last):
  File "/opt/openerp/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/openerp/addons/asterisk_click2dial/asterisk_click2dial.py", line 485, in click2dial
    % unicode(e))
except_osv: (u'Error:', u"Click to dial with Asterisk failed.\nHere is the error: '**init**() takes exactly 2 arguments (1 given)'")

**Comment by ghost** [comment]
That is coming from line 407 of /usr/local/lib/python2.7/dist-packages/Asterisk/Manager.py if you comment that line it will go all the way through.  I will submit a bug on that project, it is just the good error handling on this project is passing through the information.

**Comment by sysnoo** [comment]
Thanks,
Now it is an other error :

Click to dial with Asterisk failed.
Here is the error: 'py-Asterisk action failed: Permission denied'
Traceback (most recent call last):
  File "/opt/openerp/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/openerp/addons/asterisk_click2dial/asterisk_click2dial.py", line 485, in click2dial
    % unicode(e))
except_osv: (u'Error:', u"Click to dial with Asterisk failed.\nHere is the error: 'py-Asterisk action failed: Permission denied'")
