### ISSUE TITLE
init() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by sysnoo** [OCA/connector-telephony#82]
I am stuck with the module with this error :

Click to dial with Asterisk failed.
Here is the error: 'init() takes exactly 2 arguments (1 given)'
Traceback (most recent call last):
File "/opt/openerp/openerp/netsvc.py", line 306, in dispatch_rpc
result = ExportService.getService(service_name).dispatch(method, params)
File "/opt/openerp/openerp/service/web_services.py", line 632, in dispatch
res = fn(db, uid, params)
File "/opt/openerp/openerp/osv/osv.py", line 190, in execute_kw
return self.execute(db, uid, obj, method, *args, *kw or {})
File "/opt/openerp/openerp/osv/osv.py", line 132, in wrapper
return f(self, dbname, args, *kwargs)
File "/opt/openerp/openerp/osv/osv.py", line 199, in execute
res = self.execute_cr(cr, uid, obj, method, args, *kw)
File "/opt/openerp/openerp/osv/osv.py", line 187, in execute_cr
return getattr(object, method)(cr, uid, args, *kw)
File "/opt/openerp/openerp/addons/asterisk_click2dial/asterisk_click2dial.py", line 485, in click2dial
% unicode(e))
except_osv: (u'Error:', u"Click to dial with Asterisk failed.\nHere is the error: 'init() takes exactly 2 arguments (1 given)'")

**Comment by alexis-via** [comment]
Which version of py-Asterisk do you have ? Which version of odoo ? Which version of OCA/connector-telephony ?
