### ISSUE TITLE
Does not install on Odoo 9

### ISSUE THREAD

**Issue by jl2035** [OCA/connector-telephony#86]
I have a fresh copy of Odoo 9 and I downloaded using "wget https://github.com/OCA/connector-telephony/archive/9.0.zip". I try to install this from Apps and from command line but none works. If I browse to the module, I can only see a button 'Cancel Install' and I got no error message.

The output:

```
user@oddo9-54:/opt/odoo$ sudo -u odoo ./odoo.py -c /etc/odoo-server.conf -d mydb -i asterisk_click2dial --stop-after-init
sudo: unable to resolve host oddo9-54
2016-05-04 08:01:09,465 20110 DEBUG ? openerp.netsvc: logger level set: "openerp.workflow.workitem:WARNING"
2016-05-04 08:01:09,465 20110 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.request:INFO"
2016-05-04 08:01:09,465 20110 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.response:INFO"
2016-05-04 08:01:09,466 20110 DEBUG ? openerp.netsvc: logger level set: "openerp.addons.web.http:INFO"
2016-05-04 08:01:09,466 20110 DEBUG ? openerp.netsvc: logger level set: "openerp.sql_db:INFO"
2016-05-04 08:01:09,466 20110 DEBUG ? openerp.netsvc: logger level set: ":INFO"
2016-05-04 08:01:09,467 20110 DEBUG ? openerp.netsvc: logger level set: ":DEBUG"
2016-05-04 08:01:09,467 20110 INFO ? openerp: OpenERP version 9.0c
2016-05-04 08:01:09,467 20110 INFO ? openerp: addons paths: ['/opt/odoo/.local/share/Odoo/addons/9.0', u'/opt/odoo/addons', u'/opt/odoo/customaddons', u'/opt/odoo/voipaddons', '/opt/odoo/openerp/addons']
2016-05-04 08:01:09,468 20110 INFO ? openerp: database: odoo3@default:default
2016-05-04 08:01:09,601 20110 INFO ? openerp.service.server: Watching addons folder /opt/odoo/.local/share/Odoo/addons/9.0
2016-05-04 08:01:09,601 20110 INFO ? openerp.service.server: Watching addons folder /opt/odoo/addons
2016-05-04 08:01:09,602 20110 INFO ? openerp.service.server: Watching addons folder /opt/odoo/customaddons
2016-05-04 08:01:09,602 20110 INFO ? openerp.service.server: Watching addons folder /opt/odoo/voipaddons
2016-05-04 08:01:09,603 20110 INFO ? openerp.service.server: Watching addons folder /opt/odoo/openerp/addons
2016-05-04 08:01:09,899 20110 INFO ? openerp.service.server: AutoReload watcher running
2016-05-04 08:01:09,910 20110 DEBUG ? openerp.modules.registry: Multiprocess load registry signaling: [Registry: # 4] [Cache: # 2]
2016-05-04 08:01:09,913 20110 INFO mydb openerp.modules.loading: loading 1 modules...
2016-05-04 08:01:09,925 20110 INFO mydb openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
2016-05-04 08:01:10,225 20110 DEBUG mydb openerp.modules.loading: Updating graph with 13 more modules
2016-05-04 08:01:10,226 20110 INFO mydb openerp.modules.loading: loading 14 modules...
2016-05-04 08:01:10,232 20110 INFO mydb passlib.registry: registered crypt handler 'pbkdf2_sha512': <class 'passlib.handlers.pbkdf2.pbkdf2_sha512'>
2016-05-04 08:01:10,232 20110 INFO mydb passlib.registry: registered crypt handler 'md5_crypt': <class 'passlib.handlers.md5_crypt.md5_crypt'>
2016-05-04 08:01:10,252 20110 INFO mydb openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2016-05-04 08:01:10,272 20110 INFO mydb openerp.addons.report.models.report: Upgrade Wkhtmltopdf to (at least) 0.12.0
2016-05-04 08:01:10,304 20110 INFO mydb openerp.modules.loading: 14 modules loaded in 0.08s, 0 queries
2016-05-04 08:01:10,306 20110 WARNING mydb openerp.modules.graph: module asterisk_click2dial: not installable, skipped
2016-05-04 08:01:10,307 20110 WARNING mydb openerp.modules.graph: module base_phone: not installable, skipped
2016-05-04 08:01:10,308 20110 WARNING mydb openerp.modules.graph: Some modules were not loaded.
2016-05-04 08:01:10,308 20110 DEBUG mydb openerp.modules.loading: Updating graph with 2 more modules
2016-05-04 08:01:10,309 20110 INFO mydb openerp.modules.loading: loading 14 modules...
2016-05-04 08:01:10,309 20110 INFO mydb openerp.modules.loading: 14 modules loaded in 0.00s, 0 queries
2016-05-04 08:01:10,468 20110 INFO mydb openerp.modules.loading: Modules loaded.
2016-05-04 08:01:10,469 20110 INFO mydb openerp.modules.registry: Registry changed, signaling through the database
2016-05-04 08:01:10,470 20110 INFO mydb openerp.service.server: Stopping gracefully
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 200, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

**Comment by jl2035** [comment]
After changing Installable to True, I'm getting this:

```
2016-05-04 08:12:35,555 20737 DEBUG ? openerp.netsvc: logger level set: "openerp.workflow.workitem:WARNING"
2016-05-04 08:12:35,555 20737 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.request:INFO"
2016-05-04 08:12:35,555 20737 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.response:INFO"
2016-05-04 08:12:35,555 20737 DEBUG ? openerp.netsvc: logger level set: "openerp.addons.web.http:INFO"
2016-05-04 08:12:35,555 20737 DEBUG ? openerp.netsvc: logger level set: "openerp.sql_db:INFO"
2016-05-04 08:12:35,555 20737 DEBUG ? openerp.netsvc: logger level set: ":INFO"
2016-05-04 08:12:35,555 20737 DEBUG ? openerp.netsvc: logger level set: ":DEBUG"
2016-05-04 08:12:35,555 20737 INFO ? openerp: OpenERP version 9.0c
2016-05-04 08:12:35,555 20737 INFO ? openerp: addons paths: ['/opt/odoo/.local/share/Odoo/addons/9.0', u'/opt/odoo/addons', u'/opt/odoo/customaddons', u'/opt/odoo/voipaddons', '/opt/odoo/openerp/addons']
2016-05-04 08:12:35,556 20737 INFO ? openerp: database: odoo3@default:default
2016-05-04 08:12:35,685 20737 INFO ? openerp.service.server: Watching addons folder /opt/odoo/.local/share/Odoo/addons/9.0
2016-05-04 08:12:35,685 20737 INFO ? openerp.service.server: Watching addons folder /opt/odoo/addons
2016-05-04 08:12:35,685 20737 INFO ? openerp.service.server: Watching addons folder /opt/odoo/customaddons
2016-05-04 08:12:35,685 20737 INFO ? openerp.service.server: Watching addons folder /opt/odoo/voipaddons
2016-05-04 08:12:35,686 20737 INFO ? openerp.service.server: Watching addons folder /opt/odoo/openerp/addons
2016-05-04 08:12:35,979 20737 INFO ? openerp.service.server: AutoReload watcher running
2016-05-04 08:12:35,989 20737 DEBUG ? openerp.modules.registry: Multiprocess load registry signaling: [Registry: # 5] [Cache: # 2]
2016-05-04 08:12:35,992 20737 INFO mydb openerp.modules.loading: loading 1 modules...
2016-05-04 08:12:36,003 20737 INFO mydb openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
2016-05-04 08:12:36,201 20737 DEBUG mydb openerp.modules.loading: Updating graph with 13 more modules
2016-05-04 08:12:36,202 20737 INFO mydb openerp.modules.loading: loading 14 modules...
2016-05-04 08:12:36,207 20737 INFO mydb passlib.registry: registered crypt handler 'pbkdf2_sha512': <class 'passlib.handlers.pbkdf2.pbkdf2_sha512'>
2016-05-04 08:12:36,207 20737 INFO mydb passlib.registry: registered crypt handler 'md5_crypt': <class 'passlib.handlers.md5_crypt.md5_crypt'>
2016-05-04 08:12:36,228 20737 INFO mydb openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2016-05-04 08:12:36,247 20737 INFO mydb openerp.addons.report.models.report: Upgrade Wkhtmltopdf to (at least) 0.12.0
2016-05-04 08:12:36,278 20737 INFO mydb openerp.modules.loading: 14 modules loaded in 0.08s, 0 queries
2016-05-04 08:12:36,281 20737 DEBUG mydb openerp.modules.loading: Updating graph with 2 more modules
2016-05-04 08:12:36,281 20737 INFO mydb openerp.modules.loading: loading 16 modules...
2016-05-04 08:12:36,473 20737 INFO mydb openerp.modules.module: module base_phone: creating or updating database tables
2016-05-04 08:12:36,576 20737 INFO mydb openerp.modules.loading: loading base_phone/security/phone_security.xml
2016-05-04 08:12:36,669 20737 INFO mydb openerp.modules.loading: loading base_phone/security/ir.model.access.csv
2016-05-04 08:12:36,689 20737 INFO mydb openerp.modules.loading: loading base_phone/res_partner_view.xml
2016-05-04 08:12:36,745 20737 INFO mydb openerp.addons.base.ir.ir_ui_view: View inheritance may not use attribute 'string' as a selector.

Error context:
View `base.phone.res.partner.form`
[view_id: 224, xml_id: n/a, model: res.partner, parent_id: 123]
2016-05-04 08:12:36,745 20737 DEBUG mydb openerp.models: Exception while validating constraint
Traceback (most recent call last):
  File "/opt/odoo/openerp/models.py", line 1253, in _validate_fields
    valid = valid or fun(self._model, cr, uid, ids)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 292, in _check_xml
    self._valid_inheritance(view, view_arch)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 275, in _valid_inheritance
    self.raise_view_error(view._cr, view._uid, message, view.id)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 461, in raise_view_error
    raise AttributeError(message)
AttributeError: View inheritance may not use attribute 'string' as a selector.

Error context:
View `base.phone.res.partner.form`
[view_id: 224, xml_id: n/a, model: res.partner, parent_id: 123]
2016-05-04 08:12:36,749 20737 ERROR mydb openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1142, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4135, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4326, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `base.phone.res.partner.form`
[view_id: 224, xml_id: n/a, model: res.partner, parent_id: 123]
None" while parsing /opt/odoo/voipaddons/base_phone/res_partner_view.xml:25, near
<record id="view_partner_form" model="ir.ui.view">
    <field name="name">base.phone.res.partner.form</field>
    <field name="model">res.partner</field>
    <field name="inherit_id" ref="base.view_partner_form"/>
    <field name="arch" type="xml">
        <data><xpath expr="//group/group/field[@name='phone']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
        <xpath expr="//group/group/field[@name='mobile']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
        <xpath expr="//group/group/field[@name='fax']" position="attributes">
            <attribute name="widget">fax</attribute>
        </xpath>
        <xpath expr="//form[@string='Contact']/sheet/group/field[@name='phone']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
        <xpath expr="//form[@string='Contact']/sheet/group/field[@name='mobile']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
    </data></field>
</record>
2016-05-04 08:12:36,750 20737 CRITICAL mydb openerp.service.server: Failed to initialize database `mydb`.
Traceback (most recent call last):
  File "/opt/odoo/openerp/service/server.py", line 885, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1142, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4135, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4326, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `base.phone.res.partner.form`
[view_id: 224, xml_id: n/a, model: res.partner, parent_id: 123]
None" while parsing /opt/odoo/voipaddons/base_phone/res_partner_view.xml:25, near
<record id="view_partner_form" model="ir.ui.view">
    <field name="name">base.phone.res.partner.form</field>
    <field name="model">res.partner</field>
    <field name="inherit_id" ref="base.view_partner_form"/>
    <field name="arch" type="xml">
        <data><xpath expr="//group/group/field[@name='phone']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
        <xpath expr="//group/group/field[@name='mobile']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
        <xpath expr="//group/group/field[@name='fax']" position="attributes">
            <attribute name="widget">fax</attribute>
        </xpath>
        <xpath expr="//form[@string='Contact']/sheet/group/field[@name='phone']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
        <xpath expr="//form[@string='Contact']/sheet/group/field[@name='mobile']" position="attributes">
            <attribute name="widget">phone</attribute>
        </xpath>
    </data></field>
</record>
2016-05-04 08:12:36,751 20737 INFO mydb openerp.service.server: Stopping gracefully
2016-05-04 08:12:52,002 20758 DEBUG ? openerp.netsvc: logger level set: "openerp.workflow.workitem:WARNING"
2016-05-04 08:12:52,002 20758 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.request:INFO"
2016-05-04 08:12:52,002 20758 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.response:INFO"
2016-05-04 08:12:52,002 20758 DEBUG ? openerp.netsvc: logger level set: "openerp.addons.web.http:INFO"
2016-05-04 08:12:52,002 20758 DEBUG ? openerp.netsvc: logger level set: "openerp.sql_db:INFO"
2016-05-04 08:12:52,003 20758 DEBUG ? openerp.netsvc: logger level set: ":INFO"
2016-05-04 08:12:52,003 20758 DEBUG ? openerp.netsvc: logger level set: ":DEBUG"
2016-05-04 08:12:52,003 20758 INFO ? openerp: OpenERP version 9.0c
2016-05-04 08:12:52,003 20758 INFO ? openerp: addons paths: ['/opt/odoo/.local/share/Odoo/addons/9.0', u'/opt/odoo/addons', u'/opt/odoo/customaddons', u'/opt/odoo/voipaddons', '/opt/odoo/openerp/addons']
2016-05-04 08:12:52,003 20758 INFO ? openerp: database: odoo3@default:default
2016-05-04 08:12:52,125 20758 INFO ? openerp.service.server: Watching addons folder /opt/odoo/.local/share/Odoo/addons/9.0
2016-05-04 08:12:52,125 20758 INFO ? openerp.service.server: Watching addons folder /opt/odoo/addons
2016-05-04 08:12:52,125 20758 INFO ? openerp.service.server: Watching addons folder /opt/odoo/customaddons
2016-05-04 08:12:52,125 20758 INFO ? openerp.service.server: Watching addons folder /opt/odoo/voipaddons
2016-05-04 08:12:52,126 20758 INFO ? openerp.service.server: Watching addons folder /opt/odoo/openerp/addons
2016-05-04 08:12:52,419 20758 INFO ? openerp.service.server: AutoReload watcher running
2016-05-04 08:12:52,420 20758 DEBUG ? openerp.service.server: Multiprocess starting
2016-05-04 08:12:52,429 20777 INFO ? openerp.service.server: Worker WorkerHTTP (20777) alive
2016-05-04 08:12:52,433 20776 INFO ? openerp.service.server: Worker WorkerHTTP (20776) alive
2016-05-04 08:12:52,437 20775 INFO ? openerp.service.server: Worker WorkerHTTP (20775) alive
2016-05-04 08:12:52,441 20778 INFO ? openerp.service.server: Worker WorkerHTTP (20778) alive
2016-05-04 08:12:52,467 20781 INFO ? openerp.service.server: Worker WorkerCron (20781) alive
2016-05-04 08:12:52,469 20780 INFO ? openerp.service.server: Worker WorkerCron (20780) alive
2016-05-04 08:12:52,982 20779 DEBUG ? openerp.netsvc: logger level set: "openerp.workflow.workitem:WARNING"
2016-05-04 08:12:52,983 20779 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.request:INFO"
2016-05-04 08:12:52,983 20779 DEBUG ? openerp.netsvc: logger level set: "openerp.http.rpc.response:INFO"
2016-05-04 08:12:52,983 20779 DEBUG ? openerp.netsvc: logger level set: "openerp.addons.web.http:INFO"
2016-05-04 08:12:52,983 20779 DEBUG ? openerp.netsvc: logger level set: "openerp.sql_db:INFO"
2016-05-04 08:12:52,983 20779 DEBUG ? openerp.netsvc: logger level set: ":INFO"
2016-05-04 08:12:52,983 20779 DEBUG ? openerp.netsvc: logger level set: ":DEBUG"
2016-05-04 08:12:52,983 20779 INFO ? openerp: OpenERP version 9.0c
2016-05-04 08:12:52,983 20779 INFO ? openerp: addons paths: ['/opt/odoo/.local/share/Odoo/addons/9.0', u'/opt/odoo/addons', u'/opt/odoo/customaddons', u'/opt/odoo/voipaddons', '/opt/odoo/openerp/addons']
2016-05-04 08:12:52,984 20779 INFO ? openerp: database: odoo3@default:default
2016-05-04 08:12:53,108 20779 INFO ? openerp.service.server: Watching addons folder /opt/odoo/.local/share/Odoo/addons/9.0
2016-05-04 08:12:53,108 20779 INFO ? openerp.service.server: Watching addons folder /opt/odoo/addons
2016-05-04 08:12:53,108 20779 INFO ? openerp.service.server: Watching addons folder /opt/odoo/customaddons
2016-05-04 08:12:53,108 20779 INFO ? openerp.service.server: Watching addons folder /opt/odoo/voipaddons
2016-05-04 08:12:53,109 20779 INFO ? openerp.service.server: Watching addons folder /opt/odoo/openerp/addons
2016-05-04 08:13:09,919 20781 DEBUG ? openerp.service.server: WorkerCron (20781) polling for jobs
2016-05-04 08:13:09,923 20778 INFO ? openerp.service.server: Worker (20778) exiting. request_count: 0, registry count: 0.
2016-05-04 08:13:09,927 20777 INFO ? openerp.service.server: Worker (20777) exiting. request_count: 0, registry count: 0.
2016-05-04 08:13:09,931 20776 INFO ? openerp.service.server: Worker (20776) exiting. request_count: 0, registry count: 0.
2016-05-04 08:13:09,935 20775 INFO ? openerp.service.server: Worker (20775) exiting. request_count: 0, registry count: 0.
2016-05-04 08:13:09,939 20758 DEBUG ? openerp.service.server: Multiprocess clean stop
2016-05-04 08:13:09,939 20758 INFO ? openerp.service.server: Stopping gracefully
2016-05-04 08:13:09,943 20780 DEBUG ? openerp.service.server: WorkerCron (20780) polling for jobs
2016-05-04 08:13:09,949 20758 DEBUG ? openerp.service.server: Worker (20776) unregistered
2016-05-04 08:13:09,952 20758 DEBUG ? openerp.service.server: Worker (20775) unregistered
2016-05-04 08:13:09,953 20758 DEBUG ? openerp.service.server: Worker (20778) unregistered
2016-05-04 08:13:09,955 20758 DEBUG ? openerp.service.server: Worker (20777) unregistered
2016-05-04 08:13:10,009 20780 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'dbname=peskovnik user=odoo3 password=xxxxx'
2016-05-04 08:13:10,009 20780 DEBUG ? openerp.service.server: WorkerCron (20780) peskovnik time:0.023s mem: 842472k -> 842472k (diff: 0k)
2016-05-04 08:13:10,009 20780 INFO ? openerp.service.server: Worker (20780) exiting. request_count: 1, registry count: 0.
2016-05-04 08:13:10,022 20781 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'dbname=peskovnik user=odoo3 password=xxxxx'
2016-05-04 08:13:10,023 20781 DEBUG ? openerp.service.server: WorkerCron (20781) peskovnik time:0.028s mem: 842472k -> 842472k (diff: 0k)
2016-05-04 08:13:10,023 20781 INFO ? openerp.service.server: Worker (20781) exiting. request_count: 1, registry count: 0.
2016-05-04 08:13:10,229 20758 DEBUG ? openerp.service.server: Worker (20780) unregistered
2016-05-04 08:13:10,230 20758 DEBUG ? openerp.service.server: Worker (20781) unregistered
```

**Comment by lasley** [comment]
Hi @jl2035 - 

Thank you for the submission, but this none of these modules are compatible with version 9. This is the reason that the modules are not installable under the v9 branch, and why they error on attempted install. 

PRs are currently in review for some modules in this package; I recommend taking a look.

**Comment by sk257** [comment]
Same this problem not be solving
