### ISSUE TITLE
Fail to install Asterisk dial2call

### ISSUE THREAD

**Issue by samMalaysia** [OCA/connector-telephony#89]
Please help me on this issue... Thanks

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\http.py", line 540, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\http.py", line 577, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\http.py", line 313, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\http.py", line 310, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\http.py", line 806, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\http.py", line 406, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server\openerp\addons\base\module\module.py", line 719, in install_from_urls
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server\openerp\addons\base\module\module.py", line 651, in update_list
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\http.py", line 1313, in load_addons
  File "C:\Program Files (x86)\Odoo 8.0-20160518\server.\openerp\modules\module.py", line 80, in load_module
  File "C:\Users\HP\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\base_phone__init__.py", line 22, in <module>
  File "C:\Users\HP\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\base_phone\base_phone.py", line 27, in <module>
ImportError: No module named phonenumbers

**Comment by samMalaysia** [comment]
its installed ... 
the following step has been performed to complete the tasks.
I am in windows 10 enviornment and using odoo 8.0

assign company country in your company settings then follow below steps. 
1. pip install phonenumbers
2. pip install py-asterisk
copy both folder from python site script directory to odoo root directory
3.install based_phone 
4. install asterisk dail2call
